apiVersion: v1
kind: Service
metadata:
  name: email-service-nodeport
  namespace: default
  labels:
    app: email-service
spec:
  type: NodePort
  ports:
  - port: 8309
    targetPort: 8309
    nodePort: 30309
    protocol: TCP
    name: http
  selector:
    app: email-service
